"""Centralized validation limits for all request models.

Import and use these constants in Field() constraints so every limit
is defined in exactly one place and easy to adjust.
"""

# --- Auth ---
USERNAME_MIN = 1
USERNAME_MAX = 32
PASSWORD_MIN = 8
PASSWORD_MAX = 128
DISPLAY_NAME_MAX = 64
MFA_CODE_MAX = 32
MFA_TICKET_MAX = 256
WEBAUTHN_FIELD_MAX = 4096

# --- Users / Profiles ---
AVATAR_MAX = 512
BIO_MAX = 256
NICKNAME_MAX = 64

# --- Messages ---
MESSAGE_BODY_MAX = 4000
BULK_DELETE_MAX = 100

# --- DMs ---
GROUP_DM_RECIPIENTS_MAX = 10
DM_NAME_MAX = 64
DM_ICON_MAX = 512

# --- Channels (Feeds, Rooms, Categories, Threads) ---
CHANNEL_NAME_MIN = 1
CHANNEL_NAME_MAX = 64
TOPIC_MAX = 256

# --- Roles ---
ROLE_NAME_MIN = 1
ROLE_NAME_MAX = 64

# --- E2EE / Devices ---
DEVICE_NAME_MAX = 64
DEVICE_ID_MAX = 128
KEY_BACKUP_MAX = 1_000_000
MAX_DEVICES = 10

# --- Moderation ---
REPORT_REASON_MAX = 64
REPORT_DESCRIPTION_MAX = 2000
ADMIN_REASON_MAX = 256
KICK_REASON_MAX = 256
BAN_REASON_MAX = 256
BAN_DELETE_DAYS_MAX = 14

# --- Invites ---
INVITE_MAX_USES_MAX = 10000
INVITE_MAX_AGE_MAX = 2592000  # 30 days in seconds

# --- Server ---
SERVER_NAME_MAX = 64
SERVER_DESCRIPTION_MAX = 256
SERVER_ICON_MAX = 512

# --- Bots / Webhooks ---
WEBHOOK_NAME_MAX = 64
COMMAND_NAME_MAX = 32
COMMAND_DESCRIPTION_MAX = 256

# --- Federation ---
FEDERATION_ADDRESS_MAX = 256

# --- Pagination ---
PAGE_LIMIT_MESSAGES = 100
PAGE_LIMIT_MEMBERS = 200
PAGE_LIMIT_DMS = 100
PAGE_LIMIT_REPORTS = 100
PAGE_LIMIT_AUDIT_LOG = 100
PAGE_LIMIT_EMOJI = 200
PAGE_LIMIT_ROLES = 200
PAGE_LIMIT_SEARCH = 100
PAGE_LIMIT_INVITES = 100
PAGE_LIMIT_BANS = 200
PAGE_LIMIT_FRIENDS = 200
PAGE_LIMIT_STICKERS = 200
